version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.nl_od_demo.integrations:test
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:AWS_RDS
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:addLineItem
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:addLineitems
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.0"
- serviceName: edge.nl_od_demo.integrations:readOrdersFromRDS
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.1"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:getOrders
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.1"
- serviceName: edge.nl_od_demo.integrations:insertOrderIntoRDS
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:addCustomer
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:addOrder
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:getCustomerByZipAndName
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:getOrderNumber
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.0"
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: od.demo.services:mapLineItems
  packages:
  - name: OD_Demo_Utils
    version: "1.0"
- serviceName: edge.nl_od_demo.integrations:GetEmployees
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:Get_Employees_Limited
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.0"
- serviceName: pub.string:objectToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:getOrderDetails
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
  - name: OD_Demo_Utils
    version: "1.1"
- serviceName: od.demo.java:concatenateStrings
  packages:
  - name: OD_Demo_Utils
    version: "1.1"
packages:
- name: EdgeNL_OD_DEMO
  gitServerName: NL_MIHE_Github
  gitUrl: https://github.com/elpinjo/EdgeNL_OD_DEMO
  gitUsername: elpinjo
  gitToken: edge.scaffolding.EdgeNL_OD_DEMO.NL_MIHE_Github.gitToken
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
  wpmToken: edge.scaffolding.WmJDBCAdapter.https://packages.softwareag.com.wpmToken
- name: OD_Demo_Utils
  gitServerName: NL_MIHE_Github
  gitUrl: https://github.com/elpinjo
  gitUsername: elpinjo
  gitToken: edge.scaffolding.OD_Demo_Utils.NL_MIHE_Github.gitToken
  gitBranch: master
