version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.nl_od_demo.integrations:test
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
packages:
- name: EdgeNL_OD_DEMO
  gitServerName: NL_MIHE_Github
  gitUrl: https://github.com/elpinjo/EdgeNL_OD_DEMO
  gitUsername: elpinjo
  gitToken: edge.scaffolding.EdgeNL_OD_DEMO.NL_MIHE_Github.gitToken
  gitBranch: main
