version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.nl_od_demo.integrations:test
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:AWS_RDS
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:addLineItem
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:addLineitems
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
- serviceName: edge.nl_od_demo.integrations:readOrdersFromRDS
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
- serviceName: edge.nl_od_demo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:getOrders
  packages:
  - name: EdgeNL_OD_DEMO
    version: "1.0"
packages:
- name: EdgeNL_OD_DEMO
  gitServerName: NL_MIHE_Github
  gitUrl: https://github.com/elpinjo/EdgeNL_OD_DEMO
  gitUsername: elpinjo
  gitToken: edge.scaffolding.EdgeNL_OD_DEMO.NL_MIHE_Github.gitToken
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
  wpmToken: edge.scaffolding.WmJDBCAdapter.https://packages.softwareag.com.wpmToken
